# Pentagon numbers

# Problem 44
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


#a little calculus shows that the smallest D should be found from the smallest Pj and Pk
import copy
size=2400
def genPens(n):
    l=[]
    for i in range(1,n+1):
        l.append(int(i*(3*i-1)/2))
    return l
s1=genPens(size)
#s2=copy.deepcopy(s1)
print("genpens generated")

diff=10**10
sol=[]
count=0
begin=2100
#have tested this; to save reproduction runtime, start here
for i in range(begin,len(s1)):
    for j in range(i):
        p1=s1[i]
        p2=s1[j]
        count+=1
        if(count%10**4==0):
            print(count,' i: ',i,' j: ',j)
        if (p1+p2) in s1 and abs(p1-p2) in s1 and p1!=p2:
            if abs(p1-p2) < diff:
                diff=abs(p1-p2)
                print("diff is now",diff)
                sol=[p1,p2]
                break
    if(sol!=[]):
        pass
        break

print("answer:",diff,"; pair:",sol)
