# Triangular, pentagonal, and hexagonal

# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
# Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
# Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
size=10**6
#use dictionaries to take advantage of hash rather than list lookup
t={}
ti={}
p={}
pi={}
h={}
hi={}

for i in range(1,size+1):
    t[i]=(int(i*(i+1)/2))
    #ti[(int(i*(i+1)/2))]=i
    #p[i]=(int(i*(3*i-1)/2))
    pi[(int(i*(3*i-1)/2))]=i
    #h[i]=(int(i*(2*i-1)))
    hi[(int(i*(2*i-1)))]=i
print('sets generated')
for j in range(size):
    try:
        x=pi[t[j]]
        y=hi[t[j]]
        print('answer:',t[j])
    except:
        pass
#print('done')
