'''
Cyclical figurate numbers

Problem 61
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle        P3,n=n(n+1)/2       1, 3, 6, 10, 15, ...
Square      P4,n=n2     1, 4, 9, 16, 25, ...
Pentagonal      P5,n=n(3n−1)/2      1, 5, 12, 22, 35, ...
Hexagonal       P6,n=n(2n−1)        1, 6, 15, 28, 45, ...
Heptagonal      P7,n=n(5n−3)/2      1, 7, 18, 34, 55, ...
Octagonal       P8,n=n(3n−2)        1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
'''

#seems like there could be a number-theoretic approach.  But start with exploring
#all possibilities of 4-digit polygonal numbers
def polynum(n,i):
    if n == 3:
        return int(i*(i+1)/2)
    elif n == 4:
        return int(i**2)
    elif n == 5:
        return int(i*(3*i - 1)/2)
    elif n == 6:
        return int(i * (2*i - 1))
    elif n == 7:
        return int(i * (5*i - 3)/2)
    elif n == 8:
        return int(i * (3*i - 2))
#print("testing")
#print(polynum(3,127))
def makePolygons():
    polygons = {}
    for n in range(3, 9):
        index = 0
        current = polynum(n,index)
        while current < 1000:
            index += 1
            current = polynum(n,index)
        while current < 10000:
            try:
                polygons[n].append(current)
            except:
                polygons[n] = [current]
            index += 1
            current = polynum(n,index)
    #print(polygons)
    return polygons
polygons = makePolygons()
#---check assumption that size of polygon sets decrease as n increases
#for k,v in polygons.items():
#    print(k,len(v))
#---verified

def findCycle():
    answ = [0]
    keys=sorted(list(polygons.keys()),reverse = True)
    
    values = sorted(list(polygons.values()),reverse = True)
    
    currset = []
    for k1 in keys:
        #print('working on key {}'.format(k1))
        currset = [k1]
        for v1 in polygons[k1]:

            for k2 in keys:
                #print(' lvl2 key{}'.format(k2))
                currset = [k1]
                if k2 in currset :
                    continue
                currset = [k1, k2]
                for v2 in polygons[k2]:
                    if str(v1)[2:] != str(v2)[:2]:
                        continue
                
                    for k3 in keys:
                        #print('  lvl3 key{}'.format(k3))
                        currset = [k1, k2]
                        if k3 in currset:
                            continue
                        currset = [k1, k2, k3]
                        for v3 in polygons[k3]:
                            if str(v2)[2:] != str(v3)[:2]:
                                continue
                        
                            for k4 in keys:
                                #print('   lvl4 key{}'.format(k4))
                                currset = [k1, k2, k3]
                                if k4 in currset:
                                    continue
                                currset = [k1, k2, k3, k4]
                                for v4 in polygons[k4]:
                                    if str(v3)[2:] != str(v4)[:2]:
                                        continue
                                
                                    for k5 in keys:
                                        #print('    lvl5 key{}'.format(k5))
                                        currset = [k1, k2, k3, k4]
                                        if k5 in currset:
                                            continue
                                        currset = [k1, k2, k3, k4, k5]
                                        for v5 in polygons[k5]:
                                            if str(v4)[2:] != str(v5)[:2]:
                                                continue

                                            for k6 in keys:
                                                #print('     lvl6 key{}'.format(k6))
                                                currset = [k1, k2, k3, k4, k5]
                                                if k6 in currset:
                                                    continue
                                                currset = [k1, k2, k3, k4, k5, k6]
                                                for v6 in polygons[k6]:
                                                    if str(v5)[2:] != str(v6)[:2]:
                                                        continue
                                                    if str(v6)[2:] != str(v1)[:2]:
                                                        continue
                                                    answ = [int(v1),int(v2),int(v3),int(v4),int(v5),int(v6)]

    return answ
x=findCycle()
print(x)
print(sum(x))
